version: "3.7"
services:
    # imagem micro 02
    micro_02:
        build:
            args:
                user: sidnei
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices02
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 9002:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices02

    # imagem micro 02
    queue:
        build:
            args:
                user: sidnei
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        command: 'php artisan queue:work'
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - microservices02

    # mysql micro 02    
    db_micro_02:
        image: mariadb:10.6.10
        restart: unless-stopped
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_TCP_PORT: ${DB_PORT}
        networks:
            - microservices02

    # redis
    redis:
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - microservices02

networks:
    microservices02:
        driver: bridge
